### ISSUE TITLE
Mejor usar react-boostrap

### ISSUE THREAD

**Issue by itacademyReact** [DonatellaC/Reactube#1]
Hubiese estado bien no usar las clases de material-ui, si no los componentes:
https://material-ui.com/es/components/grid/

https://github.com/DonatellaC/Reactube/blob/7049c07de693a74846117cc6d186351970d32e73/src/App.js#L38

**Comment by DonatellaC** [comment]
Hola Luis, he modificado el estilo con los componentes de material ui. Gracias!
